name: CI/CD Pipeline

on:
  workflow_dispatch: {}  
  push:
    branches:
      - "feature/*"
      - "bugfix/*"
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up Python
      uses: actions/setup-python@v5  
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip uninstall -y torchaudio
        pip install -r requirements.txt  

    - name: Download training images if not already downloaded
      run: |
        set -e  # Exit on error
        if [ ! -f TrainingImagesPreprocessed.zip ]; then
          echo "Downloading dataset from Google Drive..."
          gdown --fuzzy https://drive.google.com/uc?id=1o50VIu51M11jbHXe5LFSVDfuQ-VNiwoS -O TrainingImagesPreprocessed.zip
        else
          echo "Dataset already downloaded, skipping."
        fi

    - name: Unzip the data into the correct directory
      run: |
        set -e  # Exit on error
        if [ ! -d "TrainingImagesPreprocessed" ]; then
          mkdir -p TrainingImagesPreprocessed
          unzip -o TrainingImagesPreprocessed.zip -d TrainingImagesPreprocessed  # Overwrite existing files
          echo "Dataset extracted successfully."
        else
          echo "Dataset already exists, skipping extraction."
        fi

    - name: Run tests with coverage
      run: pytest -v --cov=./ --cov-report=json --cov-fail-under=90



